name: Deploy to Hugging Face

# Eseguito dopo ogni push che modifica questi file
on:
  push:
    paths:
      - 'spaces/**'
      - '.github/workflows/deploy_space.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install huggingface_hub
        run: pip install huggingface_hub
      
      # Esegue push_app.py per salvare app.py su HF
      - name: Push app to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python src/push_app.py

