name: Test  

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Esegue i primi test per controllare che tutto funzioni
    - name: Test 1
      run: pytest tests/test_integration.py
    
    # Eseguo app per controllare che il modello funzioni nel secondo test
    - name: Run FastAPI app in background
      run: |
        uvicorn spaces.app:app --host 0.0.0.0 --port 8000 --reload &
        sleep 5

    - name: Test 2
      run: pytest tests/test_app.py