name: Retrain Sentiment Model

on:
  workflow_dispatch:  # trigger manuale
  schedule:
    - cron: '0 2 * * 1'  # ogni lunedì alle 02:00 UTC

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate new data batch
      run: python src/batch_manager.py

    - name: Train model
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

#    - name: Upload logs and model artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: model-and-logs
#        path: |
#          models/
#          logs/
